# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xylolink
email: webmaster@xylolink.com
slogan: L'innovation logistique et technologique au service de l'approvisionnement en bois
permalink: /:categories/:title.html
description: > # this means to ignore newlines until "baseurl:"
  Les actions de Xylolink sont principalement menées par [Adrien Arraiolos](https://www.linkedin.com/in/adrienarraiolos),
  ingénieur agronome diplômé de l'Ecole nationale Supérieure d'Agronomie de Montpellier, spécialisé dans l'innovation technologique [AgroTIC](http://www.agrotic.org/blog/).
presentation: |
  Xylolink apporte son expertise dans l'innovation logistique et technologique au service de l'approvisionnement en bois.

  Nos actions :

  * Analyse des faiblesses des réseaux logistiques par une démarche participative en entreprise,
  * Recherche des solutions les plus adaptées par une démarche d'accompagnement à l'innovation impliquant directement les collaborateurs de l'entreprise
  * Développement de solutions informatiques dédiées aux activités de la filière forêt-bois (gestion de stocks, cadencement des livraisons, analyse financière, reporting...)
  * Réalisation d'études à l'échelle de la filière (schéma de desserte, diagnostic logistique...)

  Xylolink construit une démarche d’accompagnement à la mise en oeuvre des innovations retenues, dépendant directement du niveau d’autonomie de l’entreprise. Afin que l’entreprise garde la maîtrise du processus d’innovation, Xylolink favorise la montée en compétence des acteurs par leur formation et leur implication directe à toutes les étapes.

  Xylolink est à la pointe de l'innovation de part son intégration à un large réseau académique en France et à l'international.

  Nos références : KEDGE Business School, Ecole Supérieure du Bois, ENSTIB, INRA Nancy, Laboratoire FORAC (Université Laval à Québec), Université de Bordeaux.

  Nos clients et partenaires : Les entreprises de l'approvisionnement en bois rond, les institutionnels (ORT du Grand Est, Communautés de communes MACS et Grand DAX),
   nos confrères (Forêt Logistique conseil, Cabinet Coudert)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.xylolink.com" # the base hostname & protocol for your site
twitter_username: xylolink
github_username:  xylolink
excerpt_separator: "\n"

# Build settings
markdown: kramdown

