# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xylolink - optimisation de l'approvisionnement en bois
email: webmaster@xylolink.com
slogan1: L'innovation logistique et technologique 
slogan2: Au service de l'approvisionnement en bois
permalink: /:categories/:title.html
footer: > # this means to ignore newlines until "baseurl:"
  Les actions de Xylolink sont principalement menées par [Adrien Arraiolos](https://www.linkedin.com/in/adrienarraiolos),
  ingénieur agronome diplômé de l'Ecole nationale Supérieure d'Agronomie de Montpellier, spécialisé dans l'innovation technologique [AgroTIC](http://www.agrotic.org/blog/).
baseurl: "" # the subpath of your site, e.g. /blog
description: Entreprise éditrice d'applications d'exploitation forestière
url: "https://www.xylolink.com" # the base hostname & protocol for your site
twitter_username: xylolink
github_username:  xylolink
excerpt_separator: "\n"

# Build settings
markdown: kramdown


# Gems et extensions
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Dockerfile

collections_dir: collections

collections:
  references:
  etudes:
    output: true
    permalink: /etudes/:title
  logistique:
    output: true
    permalink: /logistique/:title
  technologies:
    output: true
    permalink: /technologies/:title
  xylosuite:
    output: true
    permalink: /xylosuite/:title
  actus:
    output: true
    permalink: /actualites/:title
  
defaults:
  -
    scope:
      path: "collections/_etudes" # an empty string here means all files in the project
    values:
      icon: "fas fa-chart-area"

sass:
  sass_dir: css
  style: compressed