# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xylolink
email: webmaster@xylolink.com
slogan: L'innovation logistique et technologique au service de l'approvisionnement en bois
permalink: /:categories/:title.html
description: > # this means to ignore newlines until "baseurl:"
  Xylolink construit une démarche d’accompagnement à la mise en oeuvre des innovations retenues, dépendant directement du niveau d’autonomie de l’entreprise. Afin que l’entreprise garde la maîtrise du processus d’innovation, Xylolink favorise la montée en compétence des acteurs par leur formation et leur implication directe à toutes les étapes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xylolink.com" # the base hostname & protocol for your site
twitter_username: xylolink
github_username:  xylolink

# Build settings
markdown: kramdown

